---
title: "Analysis report by ShinyEcotox (β)"
date: "`r format(Sys.time(), '%Y/%m/%d')`"
output: word_document
---

## 0. Test type
```{r ,echo=FALSE}
if(input$test_type == 'TG201'){
  print("Test No. 201: Freshwater Alga and Cyanobacteria, Growth Inhibition Test")
}else if(input$test_type == 'TG202') {
  print("Test No. 202: Daphnia sp. Acute Immobilisation Test")
} else if(input$test_type == 'TG203') {
  print("Test No. 203: Fish, Acute Toxicity Test")
} else if(input$test_type == 'TG218') {
  print("Test No. 218: Sediment-Water Chironomid Toxicity Using Spiked Sediment or Test No. 219: Sediment-Water Chironomid Toxicity Using Spiked Water")
}else if(input$test_type == 'TG221') {
  print("Test No. 221: Lemna sp. Growth Inhibition Test")
} else if(input$test_type == 'TG235') {
  print("Test No. 235: Chironomus sp., Acute Immobilisation Test")
}  else if(input$test_type == 'TG236') {
  print("Test No. 236: Fish Embryo Acute Toxicity (FET) Test")
}  else if(input$test_type == 'TG249') {
  print("Test No. 249: Fish Cell Line Acute Toxicity")
}
print(paste("Test chemical:",input$chemical))
```
  

## 1. Summary of input data
```{r data, collapse=TRUE, echo=FALSE,warning=FALSE,fig.width=5, fig.height=5}
# Check mean and sd at each concentration
if (input$test_type == 'TG201'){
  Mean_data <- filedata() %>%
    group_by(CONC) %>%
    summarize( gr0to24 = mean(log(H24 / H0)),
            gr24to48 = mean(log(H48 / H24)),
            gr48to72 = mean(log(H72 / H48)),
            gr0to72 = mean(log(H72 / H0)/(3)),
            gr24to72 = mean(log(H72 / H24)/(2) ) ) 
  SD_data <- filedata() %>%
    group_by(CONC) %>%
    summarize( gr0to24 = sd(log(H24 / H0)),
            gr24to48 = sd(log(H48 / H24)),
            gr48to72 = sd(log(H72 / H48)),
            gr0to72 = sd(log(H72 / H0)/(3)),
            gr24to72 = sd(log(H72 / H24)/(2) ) ) 
  Mean <- filedata() %>%
  pivot_longer(cols=3:6,names_to="Time", names_pattern="H(.*)") %>%
    group_by(CONC,Time) %>% summarize(Value = mean(value)) %>%
    mutate(Concentration = as.factor(CONC)) 
  Fig <- plot(x=Mean$Time, y=Mean$Value, col=Mean$Concentration, cex=2,log="y",  xlab="Time (h)", ylab="Biomass or its surrogate")
  #legend("topleft", legend = unique(Mean$Concentration),col=unique(Mean$Concentration),pch=1,cex=1.7, inset=0.05)
  list( "Raw" = knitr::kable(filedata()) , "Growth rate: Mean" = knitr::kable( round(Mean_data,2) ),  "Growth rate: SD"=  knitr::kable( round(SD_data,2) ) )
}else if(input$test_type == 'TG202' | input$test_type == 'TG235'){
  filedata()
}else if(input$test_type == 'TG203' | input$test_type == 'TG236') {
  filedata() 
}else if(input$test_type == 'TG218') {
  summary_data <- filedata() %>%
  group_by(CONC) %>% 
  summarize_at(vars(-BEAKER),.funs= c(mean,sd)) %>%
  rename(TOTAL_mean = TOTAL_fn1, TOTAL_sd =TOTAL_fn2, DEAD_mean = DEAD_fn1, DEAD_sd = DEAD_fn2, EMERGED_mean = EMERGED_fn1, EMERGED_sd = EMERGED_fn2,  DEVELOPMENT_mean = DEVELOPMENT_fn1, DEVELOPMENT_sd = DEVELOPMENT_fn2 ) %>%
dplyr::select(CONC,	TOTAL_mean,	TOTAL_sd, DEAD_mean,DEAD_sd,EMERGED_mean,EMERGED_sd,DEVELOPMENT_mean,	DEVELOPMENT_sd)
  knitr::kable( round(summary_data,2) )
} else if (input$test_type == 'TG221'){
  Mean_data <- filedata() %>%
    group_by(CONC) %>%
    summarize( gr0to3 = mean(log(D3 / D0)/(3)),
            gr3to5 = mean(log(D5 / D3)/(2)),
            gr5to7 = mean(log(D7 / D5)/(2)),
            gr0to7 = mean(log(D7 / D0)/(7)),
            gr3to7 = mean(log(D7 / D3)/(4)) ) 
  SD_data <- filedata() %>%
    group_by(CONC) %>%
    summarize( gr0to3 = sd(log(D3 / D0)/(3)),
            gr3to5 = sd(log(D5 / D3)/(2)),
            gr5to7 = sd(log(D7 / D5)/(2)),
            gr0to7 = sd(log(D7 / D0)/(7)),
            gr3to7 = sd(log(D7 / D3)/(4)) ) 
  Mean <- filedata() %>%
    pivot_longer(cols=3:6,names_to="Time", names_pattern="D(.*)") %>%
    group_by(CONC,Time) %>% summarize(Value = mean(value)) %>%
    mutate(Concentration = as.factor(CONC)) 
  Fig <- plot(x=Mean$Time, y=Mean$Value, col=Mean$Concentration, cex=2,log="y",  xlab="Time (days)", ylab="Biomass or its surrogate")
  #legend("topleft", legend = unique(Mean$Concentration),col=unique(Mean$Concentration),pch=1,cex=1.7, inset=0.05)
  list( "Raw" = knitr::kable(filedata()), "Growth rate: Mean" = knitr::kable( round(Mean_data,2) ),  "Growth rate: SD"=  knitr::kable( round(SD_data,2) ) )
} else if(input$test_type == 'TG249') {
  summary_data <- filedata() %>%
   mutate(CONC=ifelse(CONC=="CellFree",-1,CONC)) %>%
   group_by(CONC,DYE) %>% 
   summarize_at(vars(FLUORESCENCE),.funs= c(mean,sd)) %>%
   rename(Mean = fn1, SD =fn2 ) %>%
   pivot_wider(names_from=DYE,values_from=c(Mean,SD)) %>% mutate_at(vars(CONC),as.integer) %>% arrange(CONC) %>% ungroup() %>%
   mutate(CONC=ifelse(CONC=="-1","Cellfree",CONC)) %>% mutate_at(vars(-CONC),round)
  knitr::kable( summary_data ) 
}
```

## 2. Fitting the selected model 
```{r model, collapse=TRUE, echo=FALSE}
# show the selected model
if(input$test_type == 'TG201'){
  if(input$model_TG201 =='ll2'){
  print("Selected model: Log-logistic 2 parameters")
  } else if (input$model_TG201 =='ll3'){
    print("Selected model: Log-logistic 3 parameters")
  } else if (input$model_TG201 =='ll4'){
    print("Selected model: Log-logistic 4 parameters")
  }
} else if(input$test_type == 'TG203'){
  if(input$model_TG203 =='ll2'){
  print("Selected model: Log-logistic 2 parameters")
  } else if (input$model_TG203 =='ll3'){
    print("Selected model: Log-logistic 3 parameters")
  } else if (input$model_TG203 =='ll4'){
    print("Selected model: Log-logistic 4 parameters") 
    }
} else if(input$test_type == 'TG218') {
  if(input$model_TG218_mortality == 'll2' & input$model_TG218_emergence == 'll2' & input$model_TG218_development == 'll3' ) { 
  print("Selected model: Log-logistic 2 parameters for mortality, log-logistic 2 parameters for emergence ratio, and log-logistic 3 parameters for development rate")
  } else if(input$model_TG218_mortality == 'll2' & input$model_TG218_emergence == 'll2' & input$model_TG218_development == 'll4' ) {
    print("Selected model: Log-logistic 2 parameters for mortality, log-logistic 2 parameters for emergence ratio, and log-logistic 4 parameters for development rate")
  } else if(input$model_TG218_mortality == 'll2' & input$model_TG218_emergence == 'll3' & input$model_TG218_development == 'll3' ) {
    print("Selected model: Log-logistic 2 parameters for mortality, log-logistic 3 parameters for emergence ratio, and log-logistic 3 parameters for development rate")
  } else if(input$model_TG218_mortality == 'll2' & input$model_TG218_emergence == 'll3' & input$model_TG218_development == 'll4' ) {
    print("Selected model: Log-logistic 2 parameters for mortality, log-logistic 3 parameters for emergence ratio, and log-logistic 4 parameters for development rate")
  } else if(input$model_TG218_mortality == 'll2' & input$model_TG218_emergence == 'll4' & input$model_TG218_development == 'll3' ) {
    print("Selected model: Log-logistic 2 parameters for mortality, log-logistic 4 parameters for emergence ratio, and log-logistic 3 parameters for development rate")
  } else if(input$model_TG218_mortality == 'll2' & input$model_TG218_emergence == 'll4' & input$model_TG218_development == 'll4' ) {
    print("Selected model: Log-logistic 2 parameters for mortality, log-logistic 4 parameters for emergence ratio, and log-logistic 4 parameters for development rate")
  } else if(input$model_TG218_mortality == 'll3' & input$model_TG218_emergence == 'll2' & input$model_TG218_development == 'll3' ) {
    print("Selected model: Log-logistic 3 parameters for mortality, log-logistic 2 parameters for emergence ratio, and log-logistic 3 parameters for development rate")
  } else if(input$model_TG218_mortality == 'll3' & input$model_TG218_emergence == 'll2' & input$model_TG218_development == 'll4' ) {
    print("Selected model: Log-logistic 3 parameters for mortality, log-logistic 2 parameters for emergence ratio, and log-logistic 4 parameters for development rate")
  } else if(input$model_TG218_mortality == 'll3' & input$model_TG218_emergence == 'll3' & input$model_TG218_development == 'll3' ) {
    print("Selected model: Log-logistic 3 parameters for mortality, log-logistic 3 parameters for emergence ratio, and log-logistic 3 parameters for development rate")
  } else if(input$model_TG218_mortality == 'll3' & input$model_TG218_emergence == 'll3' & input$model_TG218_development == 'll4' ) {
    print("Selected model: Log-logistic 3 parameters for mortality, log-logistic 3 parameters for emergence ratio, and log-logistic 4 parameters for development rate")
  } else if(input$model_TG218_mortality == 'll3' & input$model_TG218_emergence == 'll4' & input$model_TG218_development == 'll3' ) {
    print("Selected model: Log-logistic 3 parameters for mortality, log-logistic 4 parameters for emergence ratio, and log-logistic 3 parameters for development rate")
  } else if(input$model_TG218_mortality == 'll3' & input$model_TG218_emergence == 'll4' & input$model_TG218_development == 'll4' ) {
    print("Selected model: Log-logistic 3 parameters for mortality, log-logistic 4 parameters for emergence ratio, and log-logistic 4 parameters for development rate")
  } else if(input$model_TG218_mortality == 'll4' & input$model_TG218_emergence == 'll2' & input$model_TG218_development == 'll3' ) {
    print("Selected model: Log-logistic 4 parameters for mortality, log-logistic 2 parameters for emergence ratio, and log-logistic 3 parameters for development rate")
  } else if(input$model_TG218_mortality == 'll4' & input$model_TG218_emergence == 'll2' & input$model_TG218_development == 'll4' ) {
    print("Selected model: Log-logistic 4 parameters for mortality, log-logistic 2 parameters for emergence ratio, and log-logistic 4 parameters for development rate")
  } else if(input$model_TG218_mortality == 'll4' & input$model_TG218_emergence == 'll3' & input$model_TG218_development == 'll3' ) {
    print("Selected model: Log-logistic 4 parameters for mortality, log-logistic 3 parameters for emergence ratio, and log-logistic 3 parameters for development rate")
  } else if(input$model_TG218_mortality == 'll4' & input$model_TG218_emergence == 'll3' & input$model_TG218_development == 'll4' ) {
    print("Selected model: Log-logistic 4 parameters for mortality, log-logistic 3 parameters for emergence ratio, and log-logistic 4 parameters for development rate")
  } else if(input$model_TG218_mortality == 'll4' & input$model_TG218_emergence == 'll4' & input$model_TG218_development == 'll3' ) {
    print("Selected model: Log-logistic 4 parameters for mortality, log-logistic 4 parameters for emergence ratio, and log-logistic 3 parameters for development rate")
  } else if(input$model_TG218_mortality == 'll4' & input$model_TG218_emergence == 'll4' & input$model_TG218_development == 'll4' ) {
    print("Selected model: Log-logistic 4 parameters for mortality, log-logistic 4 parameters for emergence ratio, and log-logistic 4 parameters for development rate")
  }
} else if(input$test_type == 'TG221'){
  if(input$model_TG221 =='ll2'){
  print("Selected model: Log-logistic 2 parameters")
  } else if (input$model_TG221 =='ll3'){
    print("Selected model: Log-logistic 3 parameters")
  } else if (input$model_TG221 =='ll4'){
    print("Selected model: Log-logistic 4 parameters")
  }
} else if(input$test_type == 'TG235'){
  if(input$model_TG235 =='ll2'){
  print("Selected model: Log-logistic 2 parameters")
  } else if (input$model_TG235 =='ll4'){
    print("Selected model: Log-logistic 4 parameters")
    }
} else if(input$test_type == 'TG236'){
  if(input$model_TG236 =='ll2'){
  print("Selected model: Log-logistic 2 parameters")
  } else if (input$model_TG236 =='ll3'){
    print("Selected model: Log-logistic 3 parameters")
  } else if (input$model_TG236 =='ll4'){
    print("Selected model: Log-logistic 4 parameters")
    }
} else if(input$test_type == 'TG236'){
  if(input$model_TG249 =='ll2'){
  print("Selected model: Log-logistic 2 parameters")
    }
}
fitmodel()
knitr::kable( round(ECx(),2) )
```

## 3. Dose-response plot
```{r plot, collapse=TRUE, echo=FALSE ,fig.width=6.3, fig.height=5}
 if(input$test_type == 'TG201') {
      par(mar=c(5,10,2,2),mgp=c(3.5, 1, 0),oma=c(0.5,0.5,0.5,0.5))
      plot(fitmodel(), log="x", broken=TRUE, xlab=paste0("Concentration (", input$conc_unit, ")"), ylab="Growth rate (/d)",
             cex=2,cex.axis =2, cex.lab=2)
      } else if(input$test_type == 'TG202') {
      fit <- fitmodel()
      fit1 <- fit$fit1
      fit2 <- fit$fit2
      par(mar=c(5,10,2,2),mgp=c(3.5, 1, 0),oma=c(0.5,0.5,0.5,0.5))
      plot(fit1, log="x", broken=TRUE, xlab=paste0("Concentration (", input$conc_unit, ")"), ylab="Mortality", 
           ylim=c(0,1),lty="dotted",cex=1.5,cex.axis =1.5, cex.lab=1.5)
      par(new=TRUE)
      plot(fit2, log="x", broken=TRUE, xlab="", ylab="", main="",
           ylim=c(0,1), col="#D55E00",cex=1.5,cex.axis =1.5, cex.lab=1.5)
      legend("topleft",inset=0.05, legend = c("24 h","48 h"), col = c("black","#D55E00"), lty = c("dotted","solid"),cex=1.5)
    } else if(input$test_type == 'TG203') {
      fit <- fitmodel()
      fit1 <- fit$fit1
      fit2 <- fit$fit2
      fit3 <- fit$fit3
      fit4 <- fit$fit4
      par(mar=c(5,10,2,2),mgp=c(3.5, 1, 0),oma=c(0.5,0.5,0.5,0.5))
      plot(fit1, log="x", broken=TRUE, xlab=paste0("Concentration (", input$conc_unit, ")"), ylab="Mortality", 
           ylim=c(0,1),lty="dotted",cex=2,cex.axis =1.5, cex.lab=1.5)
      par(new=TRUE)
      plot(fit2, log="x", broken=TRUE, xlab="", ylab="", main="",
           ylim=c(0,1), col="#D55E00",cex=1.5,cex.axis =1.5, cex.lab=1.5)
      par(new=TRUE)
      plot(fit3, log="x", broken=TRUE, xlab="", ylab="", main="",
           ylim=c(0,1), lty="dotted", col="tomato",cex=1.5,cex.axis =1.5, cex.lab=1.5)
      par(new=TRUE)
      plot(fit4, log="x", broken=TRUE, xlab="", ylab="", main="",
           ylim=c(0,1), col="black",cex=1.5,cex.axis =1.5, cex.lab=1.5)
      legend("topleft",inset=0.05, legend = c("24 h","48 h","72 h","96 h"), col = c("black","#D55E00","tomato","black"), lty = c("dotted","solid","dotted","solid"),cex=1.5)
    } else if(intest_type() == 'TG218') {
      fit <- fitmodel()
      fit1 <- fit$fit1
      fit2 <- fit$fit2
      fit3 <- fit$fit3
#　　 par(mar=c(5,8,2,2), mfrow=c(3,1),mgp=c(3, 1, 0) )
      knitr::opts_chunk$set(fig.width=6, fig.height=19) 
      plot(fit1, log="x", broken=TRUE, xlab=paste0("Concentration (", input$conc_unit, ")"), ylab="Mortality",
           ylim=c(0,1),lty="dotted",cex=2,cex.axis =1.2, cex.lab=1.2)
      plot(fit2, log="x", broken=TRUE, xlab=paste0("Concentration (", input$conc_unit, ")"), ylab="Emergence ratio",
           ylim=c(0,1),lty="dotted",cex=2,cex.axis =1.2, cex.lab=1.2)
      plot(fit3, log="x", broken=TRUE, xlab=paste0("Concentration (", input$conc_unit, ")"), ylab="Development rate",
           lty="dotted",cex=2,cex.axis =1.2, cex.lab=1.2)
    } else if(input$test_type == 'TG221') {
      par(mar=c(5,10,2,2),mgp=c(3.5, 1, 0),oma=c(0.5,0.5,0.5,0.5))
      plot(fitmodel(), log="x", broken=TRUE, xlab=paste0("Concentration (", input$conc_unit, ")"), ylab="Growth rate (/d)",
             cex=2,cex.axis =2, cex.lab=2)
    } else if(input$test_type == 'TG235') {
      fit <- fitmodel()
      fit1 <- fit$fit1
      fit2 <- fit$fit2
      par(mar=c(5,8,2,2),mgp=c(3, 1, 0))
      plot(fit1, log="x", broken=TRUE, xlab=paste0("Concentration (", input$conc_unit, ")"), ylab="Immobility",
           ylim=c(0,1),lty="dotted",cex=1.5,cex.axis =1.5, cex.lab=1.5)
      par(new=TRUE)
      plot(fit2, log="x", broken=TRUE, xlab="", ylab="", main="",
           ylim=c(0,1), col="#D55E00",cex=1.5,cex.axis =1.5, cex.lab=1.5)
      legend("topleft",inset=0.05, legend = c("24 h","48 h"), col = c("black","#D55E00"), lty = c("dotted","solid"),cex=1.5)
    }  else if(input$test_type == 'TG236') {
      fit <- fitmodel()
      fit1 <- fit$fit1
      fit2 <- fit$fit2
      fit3 <- fit$fit3
      fit4 <- fit$fit4
      par(mar=c(5,8,2,2),mgp=c(3, 1, 0))
      plot(fit1, log="x", broken=TRUE, xlab=paste0("Concentration (", input$conc_unit, ")"), ylab="Mortality", 
           ylim=c(0,1),lty="dotted",cex=2,cex.axis =1.5, cex.lab=1.5)
      par(new=TRUE)
      plot(fit2, log="x", broken=TRUE, xlab="", ylab="", main="",
           ylim=c(0,1), col="#D55E00",cex=1.5,cex.axis =1.5, cex.lab=1.5)
      par(new=TRUE)
      plot(fit3, log="x", broken=TRUE, xlab="", ylab="", main="",
           ylim=c(0,1), lty="dotted", col="tomato",cex=1.5,cex.axis =1.5, cex.lab=1.5)
      par(new=TRUE)
      plot(fit4, log="x", broken=TRUE, xlab="", ylab="", main="",
           ylim=c(0,1), col="black",cex=1.5,cex.axis =1.5, cex.lab=1.5)
      legend("topleft",inset=0.05, legend = c("24 h","48 h","72 h","96 h"), col = c("black","#D55E00","tomato","black"), lty = c("dotted","solid","dotted","solid"),cex=1.5)
    } else if(input$test_type == 'TG249') {
      fit <- fitmodel()
      fit1 <- fit$fit1
      fit2 <- fit$fit2
      fit3 <- fit$fit3
      par(mar=c(5,8,2,2))
      plot(fit1, log="x", broken=TRUE, xlab=paste0("Concentration (", input$conc_unit, ")"), ylab="Cell viability", 
           ylim=c(0,1),lty="solid",col="#0072B2",cex=2,cex.axis =2, cex.lab=2)
      par(new=TRUE)
      plot(fit2, log="x", broken=TRUE, xlab="", ylab="", main="",
           ylim=c(0,1), lty="dotted",col="#009E73",cex=2,cex.axis =2, cex.lab=2)
      par(new=TRUE)
      plot(fit3, log="x", broken=TRUE, xlab="", ylab="", main="",
           ylim=c(0,1), lty="solid", col="#D55E00",cex=2,cex.axis =2, cex.lab=2)
      legend("bottomleft",inset=0.05, legend = c("almarBlue","CFDA-AM","Neutral Red"), col = c("#0072B2","#009E73","#D55E00"), lty = c("solid","dotted","solid"),cex=1.1)
    }
```

## 4. Hypothesis testing
```{r hypothesis_testing,echo=FALSE}
if(input$test_type == 'TG201'){
        if(input$test_method_TG201=='Dunnett'){
          print("Growth rate: analyzed by Dunnett's test")
          print("summary (glht (fit, linfct=mcp (CONC='Dunnett'), alternative='less'))")
        } else if(input$test_method_TG201=='Steel'){
          print("Growth rate: analyzed by Steel's test")
          print('steel.test(gr0to72 ~ CONC, data = growth_df, control = "0", alternative="less")')
          print("Steel's test: 'https://www.trifields.jp/introducing-steel-in-r-1637'")
        }
  }else if(input$test_type == 'TG202'){
    print("No hypothesis test was performed.")
  }else if(input$test_type == 'TG203'){
    print("NOEC, an optional toxicity value, was estimated by Fisher's exact test with Bonferroni-Holm correction correction.")
    print('fisher <- function(a,b,c,d){ dt <- matrix(c(a,b,c,d),ncol=2)')
    print('c(pvalue = fisher.test(dt)$p.value)}')
    print('pvalue <- fisher(DEAD,TOTAL-DEAD, DEAD_ctrl,TOTAL_ctrl-DEAD_ctrl))' )
    } else if(input$test_type == 'TG218'){
      if(input$test_method_TG218_mortality=='CA'){
        print("Mortality: analyzed by step-down Cochran-Armitage test")
        } else if(input$test_method_TG218_mortality=='Fisher'){
          print("Mortality: analyzed by Fisher's exact test")
          }
      if(input$test_method_TG218_emergence=='CA'){
        print("Emergence ratio: analyzed by step-down Cochran-Armitage test")
        } else if(input$test_method_TG218_emergence=='Fisher'){
          print("Emergence ratio: analyzed by Fisher's exact test")
          }
      if(input$test_method_TG218_development=='Fisher'){
        print("Development rate: analyzed by step-down Cochran-Armitage test")
        } else if(input$test_method_TG218_development=='Dunnett'){
          print("Development rate: analyzed by Dunnett's test")
        } else if(input$test_method_TG218_development=='Steel'){
          print("Development rate: analyzed by Steel's test")
        }
    } else if(input$test_type == 'TG221'){
        if(input$test_method_TG221=='Dunnett'){
          print("Growth rate: analyzed by Dunnett's test")
          print("summary (glht (fit, linfct=mcp (CONC='Dunnett'), alternative='less'))")
        } else if(input$test_method_TG221=='Steel'){
          print("Growth rate: analyzed by Steel's test")
          print('steel.test(gr0to7 ~ CONC, data = growth_df, control = "0", alternative="less")')
          print("Steel's test: 'https://www.trifields.jp/introducing-steel-in-r-1637'")
          }
    } else if(input$test_type == 'TG235'){
        print("NOEC, an optional toxicity value, was estimated by Fisher's exact test with Bonferroni-Holm correction correction.")
        print( 'fisher <- function(a,b,c,d){ dt <- matrix(c(a,b,c,d),ncol=2)')
        print( 'c(pvalue = fisher.test(dt)$p.value)}')
        print( 'pvalue <- fisher(IMMOBILIZED,TOTAL-IMMOBILIZED, IMMOBILIZED_ctrl,TOTAL_ctrl-IMMOBILIZED_ctrl))' )
    } else if(input$test_type == 'TG236'){
        print("No hypothesis test was performed")
    }  else if(input$test_type=='TG249'){
      print("CEll viability: analyzed by Dunnett's test")
      print("fit3 <- aov( FLUORESCENCE ~ CONC, data = NeutralRed  )")
      print( 'Res1 <- summary (glht (fit3, linfct=mcp (CONC="Dunnett"), alternative="less"))') 
}
TestResult()
```


## 5. Session Info
```{r sessionInfo}
sessionInfo()
```
